cors:
  originPatterns: http://localhost:8080,http://localhost:3000,http://erudio.com.br
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000 # 1 hora
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
    username: root
    password: myAdmin4774
  
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
        
springdoc:
  paths-to-match: 
    - /**/v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true